plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id "maven-publish"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven { url = "https://masa.dy.fi/maven/sakura-ryoko"
        content {includeGroupAndSubgroups("fi.dy.masa")}
    }
    maven { url = 'https://maven.terraformersmc.com/releases' }
    maven { url = 'https://www.cursemaven.com' }
    maven { url = 'https://maven.fallenbreath.me/jitpack' }
    maven { url = 'https://maven.fallenbreath.me/releases' }
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

    implementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"
    implementation "maven.modrinth:modmenu:${project.mod_menu_version}"

    implementation("me.fallenbreath:conditional-mixin-fabric:${project.conditionalmixin_version}")
    compileOnly "maven.modrinth:iris:${project.iris_version}"
    compileOnly "maven.modrinth:sodium:${project.sodium_version}"
    compileOnly "fi.dy.masa.litematica:litematica-fabric-${project.minecraft_version}:${project.litematica_version}"
}


processResources {
    dependsOn project(":common").tasks.processResources
    from project(":common").sourceSets.main.resources

    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

shadowJar {
    exclude "META-INF/neoforge.mods.toml"
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveFileName = "${project.archives_base_name}-${project.version}-mc${project.minecraft_version}-fabric.jar"
    archiveClassifier = null

}