plugins {
    id 'architectury-plugin' version '3.5-SNAPSHOT'
    id 'dev.architectury.loom-no-remap' version '1.17-SNAPSHOT' apply false
    id 'java'
}

subprojects {
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom-no-remap'
    apply plugin: 'maven-publish'

    group = rootProject.maven_group
    version = rootProject.mod_version

    repositories {
        mavenCentral()
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://maven.neoforged.net/releases/") }
        maven { url = uri("https://maven.architectury.dev/") }
    }
}