org.gradle.jvmargs=-Xmx1G

# Minecraft
minecraft_version=1.21.11

# Mod Properties
mod_version=0.2.1
maven_group=ink.mingyuan
archives_base_name=tweelix
architectury_api_version =
# Fabric
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Fabric Mod
fabric_version=0.141.3+1.21.11

mod_menu_version=17.0.0-beta.1

iris_version=1.10.6+1.21.11-fabric

sodium_version=mc1.21.11-0.8.6-fabric

malilib_version = 0.27.12

litematica_version = 1.21.11-0.26.1

tweakeroo_version = 1.21.11-0.27.0

neoforge_version=21.11.33-beta

mafglib_version=0.4.4+mc1.21.11

conditionalmixin_version=0.6.4