
architectury {
    common("fabric", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/tweelix.accessWidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven" }
}


dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "maven.modrinth:malilib:${project.malilib_version}"

    implementation "maven.modrinth:litematica:${project.litematica_version}"
}

configurations {
    namedElements {
        canBeResolved = false
        canBeConsumed = true
    }
}

tasks.register('namedJar', Jar) {
    from sourceSets.main.output
    archiveClassifier = 'named'
}

artifacts {
    namedElements namedJar
}