
architectury {
    common("fabric", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/tweelix.accessWidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    mavenCentral()
    maven {
        url = "https://api.modrinth.com/maven" }
    maven { url = "https://masa.dy.fi/maven/sakura-ryoko"
        content {includeGroupAndSubgroups("fi.dy.masa")}
    }
    maven { url = 'https://maven.fallenbreath.me/releases'
        content {includeGroupAndSubgroups("me.fallenbreath")}
    }
    maven { url = 'https://maven.terraformersmc.com/releases/'
        content { includeGroupAndSubgroups("com.terraformersmc")}
    }

    maven { url = 'https://jitpack.io'
        content { includeGroupAndSubgroups("com.github")}
    }
    maven { url = 'https://maven.terraformersmc.com/releases' }
    maven { url = 'https://www.cursemaven.com' }
    maven { url = "https://api.modrinth.com/maven" }

}


dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "me.fallenbreath:conditional-mixin-fabric:${project.conditionalmixin_version}"

    implementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"
    implementation "maven.modrinth:modmenu:${project.mod_menu_version}"
    compileOnly "maven.modrinth:litematica:${project.litematica_version}"
}

configurations {
    namedElements {
        canBeResolved = false
        canBeConsumed = true
    }
}

tasks.register('namedJar', Jar) {
    from sourceSets.main.output
    archiveClassifier = 'named'
}

artifacts {
    namedElements namedJar
}