
architectury {
    common("fabric", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/tweelix.accessWidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven { url = "https://masa.dy.fi/maven/sakura-ryoko"
        content {includeGroupAndSubgroups("fi.dy.masa")}
    }
    maven { url = 'https://maven.fallenbreath.me/releases'
        content {includeGroupAndSubgroups("me.fallenbreath")}
    }
    maven {
        url = "https://api.modrinth.com/maven" }
}


dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"

    implementation  "fi.dy.masa.litematica:litematica-fabric-${project.minecraft_version}:${project.litematica_version}"

    include(implementation("me.fallenbreath:conditional-mixin-fabric:${project.conditionalmixin_version}"))

    compileOnly "maven.modrinth:iris:${project.iris_version}"

}

configurations {
    namedElements {
        canBeResolved = false
        canBeConsumed = true
    }
}

tasks.register('namedJar', Jar) {
    from sourceSets.main.output
    archiveClassifier = 'named'
}

artifacts {
    namedElements namedJar
}

jar.enabled = false