modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/mingyuan3709/tweelix/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "tweelix"
version = "${version}"
displayName = "Tweelix"
authors = "ming_yuan"
description = '''
一个面向原版生存的轻量客户端辅助模组
A vanilla-focused lightweight client-side utility mod.
'''
logoFile = "assets/tweelix/icon.png"

[[dependencies.tweelix]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tweelix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tweelix.mixins.json"
