modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "tweelix"
version = "${version}"
displayName = "Tweelix"
authors = "ming_yuan"
description = '''

'''
logoFile = "assets/tweelix/icon.png"

[[dependencies.tweelix]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tweelix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tweelix.mixins.json"
