plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id "maven-publish"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/tweelix.accesswidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom(common)
    runtimeClasspath.extendsFrom(common)
    developmentNeoForge.extendsFrom(common)
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven" }

    maven {url = 'https://maven.fallenbreath.me/releases'
        content {includeGroupAndSubgroups("me.fallenbreath")}
    }

    maven {
        url = "https://dl.cloudsmith.io/public/thinkingstudio/forgifiedfabricapi/maven/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }

    modImplementation "maven.modrinth:mafglib:${project.mafglib_version}"

    include(implementation("me.fallenbreath:conditional-mixin-${loom.platform.get().id()}:${project.conditionalmixin_version}"))

    // ForgifiedFabricAPI — ForgeMatica 所需的 Fabric API 兼容层
    //modImplementation("org.sinytra.forgified-fabric-api:fabric-api-base:0.4.42+d1308ded49") { transitive = false }
    //modImplementation("org.sinytra.forgified-fabric-api:fabric-networking-api-v1:4.3.3+e76757cb6c") { transitive = false }

    //modImplementation "maven.modrinth:forgematica:${project.forgematica_version}"
}

processResources {

    // 1. 声明依赖于 common 模块的 processResources 结果
    dependsOn project(":common").tasks.processResources

    // 2. 引入公共模块的资源文件
    from project(":common").sourceSets.main.resources

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
    inputs.property "META-INF/neoforge.mods.toml", project.version
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "tweelix.accessWidener"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "shadow"
}

jar {
    archiveClassifier = "bare"
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier = null
}