plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id "maven-publish"
}

architectury {
    platformSetupLoomIde()
    neoForge()

}

base {
    archivesName = project.archives_base_name
}


tasks.named('shadowJar') {
    archiveFileName = "${project.archives_base_name}-${project.version}-mc${project.minecraft_version}-neoforge.jar"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = 'https://maven.fallenbreath.me/releases'
        content { includeGroupAndSubgroups("me.fallenbreath") }
    }
    maven { url = "https://dl.cloudsmith.io/public/thinkingstudio/forgifiedfabricapi/maven/" }
}

dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }

    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }

    implementation "maven.modrinth:mafglib:${project.mafglib_version}"

    implementation "maven.modrinth:foxifiedclasstweaker:${project.foxified_classtweaker_version}"

    implementation "me.fallenbreath:conditional-mixin-neoforge:${project.conditionalmixin_version}"
}

processResources {
    dependsOn project(":common").tasks.processResources
    from project(":common").sourceSets.main.resources

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
    inputs.property "META-INF/neoforge.mods.toml", project.version
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "tweelix.accessWidener"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null  // 最终产物
}

jar {
    archiveClassifier = "bare"
}